apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-sriov
  namespace: ran-subscriptions
placementRef:
  name: placement-policy-sriov
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-sriov-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
