apiVersion: policyGenerator/v1
kind: PolicyGenerator
metadata:
  name: acm-policy
  namespace: acm-policy-generator
# The arguments should be given and defined as below with same order --ranGenPath= --sourcePath= --outPath= --stdout
argsOneLiner: ./ran-gen ./source-policies ./manifests true false


