apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-sample-site-du-policy-node-autolabeler
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: [sample-du-cluster]}
