apiVersion: v1
kind: Namespace
metadata:
  name: sample-du-sno-site1-cluster
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: sample-du-sno-site1-cluster
    profile: du-sno
    hardwareType: dell
  name: sample-du-sno-site1-cluster
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: sample-du-sno-site1-cluster
  namespace: sample-du-sno-site1-cluster
spec:
  clusterName: sample-du-sno-site1-cluster
  clusterNamespace: sample-du-sno-site1-cluster
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.1.0
