apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: site-du-sno-1-policies-placementrule
    namespace: sites-sub
spec:
    clusterSelector:
        matchExpressions:
            - key: sites
              operator: In
              values:
                - site-du-sno-1
