apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: site-du-sno-1-policies-placementbinding
    namespace: sites-sub
placementRef:
    name: site-du-sno-1-policies-placementrule
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: site-du-sno-1-sriov-nw-fh-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: site-du-sno-1-sriov-nnp-fh-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: site-du-sno-1-sriov-nw-mh-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: site-du-sno-1-sriov-nnp-mh-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: site-du-sno-1-perfprofile-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
