apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: group-du-sno-policies-placementbinding
    namespace: groups-sub
placementRef:
    name: group-du-sno-policies-placementrule
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: group-du-sno-label-deploy-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-label-configmap-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-label-ns-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-label-role-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-log-forwarder-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-log-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-mc-sctp-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-mc-chronyd-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-ptp-config-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-du-sno-sriov-operconfig-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
