apiVersion: v1
kind: Namespace
metadata:
  name: cnf-cu-du-site-cluster
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: cnf-cu-du-site-cluster
    profile: cu-du
  name: cnf-cu-du-site-cluster
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cnf-cu-du-site-cluster
  namespace: cnf-cu-du-site-cluster
spec:
  clusterName: cnf-cu-du-site-cluster
  clusterNamespace: cnf-cu-du-site-cluster
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.1.0
