apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cnfcu-sriov-network
  namespace: sites-ran-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["cnf-cu-du-site-cluster"]}
