apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-du-sriov-network-node-policy
placementRef:
  name: placement-policy-du-sriov-network-node-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-du-sriov-network-node-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
