apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: group-du-policies-placementbinding
    namespace: groups-sub
placementRef:
    name: group-du-policies-placementrule
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: group-du-mcp-worker-du-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
