apiVersion: v1
kind: Namespace
metadata:
  name: sample-cu-cluster
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: sample-cu-cluster
    profile: cu
  name: sample-cu-cluster
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: sample-cu-cluster
  namespace: sample-cu-cluster
spec:
  clusterName: sample-cu-cluster
  clusterNamespace: sample-cu-cluster
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.0.0
