---
apiVersion: v1
kind: Namespace
metadata:
  name: sites-ran-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moc-sites
  namespace: sites-ran-sub
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: manifests/moc-sites
    repoURL: https://github.com/TheRealHaoLiu/ztp-ran-manifests/
    targetRevision: scale-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
