apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: group-du-sno-policies-placementbinding
    namespace: groups-sub
placementRef:
    name: group-du-sno-policies-placementrule
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: group-sno-du-console-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
# commented out due to lack of kafka instance in our test environment
#    - name: group-sno-du-log-forwarder-policy
#      kind: Policy
#      apiGroup: policy.open-cluster-management.io
    - name: group-sno-du-log-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-sno-du-mc-sctp-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-sno-du-mc-chronyd-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-sno-du-ptp-config-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: group-sno-du-sriov-operconfig-policy
      kind: Policy
      apiGroup: policy.open-cluster-management.io
