apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: site-sno00424-configmap-policy-placementrule
    namespace: sites-sub
spec:
    clusterSelector:
        matchExpressions:
            - key: name
              operator: In
              values:
                - sno00424
