---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hack-ran-subscription
  namespace: hack-ran-sub
spec:
  type: GitHub
  pathname: https://github.com/TheRealHaoLiu/ztp-ran-manifests
