apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: cnfde6-du-sno-placementbinding
    namespace: sites-ran-subscriptions
placementRef:
    name: cnfde6-du-sno-placementrule
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: cnfde6-du-sno-sriovnetwork
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: cnfde6-du-sno-sriovnetworknode
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: cnfde6-du-sno-sriovnetwork
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: cnfde6-du-sno-sriovnetworknode
      kind: Policy
      apiGroup: policy.open-cluster-management.io
    - name: cnfde6-du-sno-perfprofile
      kind: Policy
      apiGroup: policy.open-cluster-management.io
