---
apiVersion: ranPolicyGenerator/v1
kind: RanGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-du-rwn-policies"
  namespace: "policy-template"
  labels:
    common: false
    groupName: "group-du-rwn"
    siteName: "N/A"
    # In this example we used the MCP=worker-du for group-du-sno to let the clusters that will be under group-du-sno also have the policies for group-du
    mcp: "node-du"
sourceFiles:
  - fileName: MachineConfigPool
    # For MCP policy name is used to deifne the role name and node label.
    # The name will be used as the NodeSelector value in other policies that is should be applied only for this MachineConfigPool
    name: "node-du"
  - fileName: AutolabelDeployment
    name: "N/A"
    spec:
       template:
         spec:
           tolerations:
           - effect: NoSchedule
             key: node-role.kubernetes.io/master
             operator: Exists
  - fileName: AutolabelConfigMap
    name: "N/A"
    data:
      rules1.properties: |
        name: cnf*
        labels:
        - node-role.kubernetes.io/node-du

