---
apiVersion: ranPolicyGenerator/v1
kind: RanGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-du-policies"
  namespace: "policy-template"
  labels:
    common: false
    groupName: "group-du"
    siteName: "N/A"
    mcp: "worker-du"
# sourceFiles.fileName values should be same as file name in the sourcePolicies dir without .yaml extension
sourceFiles:
  - fileName: MCP-worker-du
    policyName: "mcp-worker-du-policy"
