apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-du-dell-sriov-network
  namespace: hw-type-ran-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - {key: hardwareType, operator: In, values: ["dell"]}
